### ISSUE TITLE
[l10n] Missing/wrong l10n note

### ISSUE THREAD

**Issue by StoyanDimitrov** [vslavik/winsparkle#153]
The [string in question](https://github.com/vslavik/winsparkle/blob/master/translations/winsparkle.pot#L99), [source file](https://github.com/vslavik/winsparkle/blob/57aef82203d82a322fc3dddb9eee81c790c5fc64/src/ui.cpp#L857). It's wrong because of parse error of some kind but adding translator note will be of help here.

**Comment by vslavik** [comment]
I'm sorry, but I literally have no idea what you're talking about, what you think is wrong (or *why*) or what you think should be done instead. Please read [this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and provide more comprehensible bug report including basic information and an explanation. And if you think something should be changed, why not submit a PR with the chance?

**Comment by StoyanDimitrov** [comment]
Oh, yes, I've omitted a lot of information here.
In WinSparkle_winsparkle_bg.po downloaded from Crowdin with PoEdit I see the following comment that does not correspond to the string beneath.

> #. TRANSLATORS: This is the progress of a download, e.g. "3 MB of 12 MB".
> #: src/ui.cpp:732
> #, c-format
> msgid "%s %s is now available (you have %s). Would you like to download it now?"

It could be bug in the Crowdin, still the string could benefit from translator comment. One particular reason is that there are 3 placeholders and unclear which is what.

**Comment by vslavik** [comment]
There are screenshots in the Crowdin UI — they make this string rather obvious. If you think this string would benefit from a translator note, do it and submit a PR (it would take you less time then we both spent on this issue by now…). If you're referring to some mixup in crowdin project (i.e. nothing to do with *this* place, i.e. should been reported over there, not here), I think I fixed that. If you mean something else, I still don't understand what.

**Comment by StoyanDimitrov** [comment]
This string will benefit from translator comment. That's the point. And I'm rising the issue for that purpose. Translating the project from Poedit does not show the screenshot that Crowdin shows so for me it is useless and the string still does not have context. I will not use Crowdin for reasons beyond the scope of this conversation. For me not using Crowdin is valid way of consuming translation files. It's up to you what usecases you want to support. I'm just giving you hint.

P.S.
The last couple of times I interact with you I'm left with a bitter taste in my mouth. Not that you don't fulfil my geeky requirements but because you sound so rude and arrogant. Please be more polite and respectful.

**Comment by vslavik** [comment]
> I'm just giving you hint.

Respectfully, "hints" are a dime a dozen. Actual *work*, however trivial on improvements, is what is valuable.

And make no mistake: I asked you to contribute back a minute or two of your time *on something that you care about* more than I do. I happen to disagree with your opinion, because I happen to think that the screenshot in Crowdin is the best kind of explanation and I do think that translations should go through Crowdin. But I respect your right to have a different opinion and if you want to follow through on your conviction, I would *welcome* such PR — even though it would go against *my* opinion. But you're asking *me* to do work that you want, but I disagree with, even though you yourself don't care enough about it to invest a minute or two into it. That's a bit ridiculous position to take, no?

I consider this closed as WONTFIX — as in, *I* won't. You're welcome to.

> so rude and arrogant

Let's review, shall we. You submitted an issue that was incoherent babbling that I *still* can't make any sense of, even after you semi-explained what you meant. I called you out and asked to do a better job. If that is "arrogant" to you, you're some precious little flower. Perhaps you should instead have a hard look at *your* entitled and inappropriate attitude (such as asking me for free labor to fulfill your whims) and how it might affect the welcome you get, and tone down the preaching.
